# Common Labels
labels:
  app: "uba-cronjob"
  group: "digit-works"

namespace: egov

# Ingress Configs
ingress:
  namespace: egov
  enabled: false  # Not needed for a cron job
  zuul: true
  context: "uba-cronjob"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "prsm323/ubacronjob"  # Your Docker image repository
  tag: latest  # Ensure this matches your built Docker image tag
replicas: "1"
healthChecks:
  enabled: false  # Not needed for cron jobs
memory_limits: 384Mi

# CronJob Schedule Configuration
cronjob:
  enabled: true
  schedule: "*/10 * * * *"  # This will run the cron job every 10 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: uba-cronjob
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"  # Image from values.yaml
              env: []
          restartPolicy: OnFailure  # The job will be retried if it fails

# Additional Container Envs (if needed)
env: []
