# Common Labels
labels:
  app: "uba-cronjob"
  group: "digit-works"

namespace: egov

# Ingress Configs
ingress:
  namespace: egov
  enabled: false  # Not needed for a cron job
  zuul: true
  context: "uba-cronjob"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "prsm323/ubacronjob"  
  tag: dev
replicas: "1"
memory_limits: 384Mi

# Additional Container Envs (if needed)
env: []
