# Common Labels
labels:
  app: "uba-cronjob"
  group: "digit-works"

namespace: egov

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "uba-cronjob"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "prsm323/ubacronjob"  # Docker image repository for cron job
  tag: latest  # Docker image tag (e.g., latest)
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/ubacronjob/health"
  readinessProbePath: "/ubacronjob/health"
memory_limits: 384Mi

# CronJob Schedule Configuration
cronjob:
  enabled: true  # Enable the cron job
  schedule: "*/10 * * * *"  # Schedule to run every 10 minutes (Cron syntax)
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: uba-cronjob
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              env:
                - name: JAVA_OPTS
                  value: {{ .Values.heap | quote }}
                - name: JAVA_ARGS
                  value: {{ .Values.java-args | quote }}
                {{- if .Values.tracing-enabled }}
                - name: TRACER_OPENTRACING_ENABLED
                  value: "true"
                {{- end }}
                - name: SERVER_CONTEXT_PATH
                  value: /uba-cronjob
                - name: SERVER_SERVLET_CONTEXT_PATH
                  value: /uba-cronjob
          restartPolicy: OnFailure  # Restart the cron job pod if it fails

# Additional Container Envs
env: |
  - name: JAVA_OPTS
    value: {{ .Values.heap | quote }}
  - name: JAVA_ARGS
    value: {{ .Values.java-args | quote }}
  {{- if .Values.tracing-enabled }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true"
  {{- end }}
  - name: SERVER_CONTEXT_PATH
    value: /uba-cronjob
  - name: SERVER_SERVLET_CONTEXT_PATH
    value: /uba-cronjob
