{{- with index .Values "secrets" "git-sync" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  ssh: {{ .ssh | b64enc | quote }}
  known_hosts: {{ .known_hosts | b64enc | quote }}
{{- end }}
# Debugging output
{{- printf "ssh: %v" (index .Values "secrets" "git-sync" "ssh") | quote }}
{{- printf "known_hosts: %v" (index .Values "secrets" "git-sync" "known_hosts") | quote }}

