{{- with index .Values "secrets" "git-sync" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name | default "git-sync-secret" }}
  namespace: {{ .namespace | default "default" }}
type: Opaque
data:
  ssh: {{ .ssh | default "" | b64enc | quote }}
  known_hosts: {{ .known_hosts | default "" | b64enc | quote }}
{{- end }}

