name: DIGIT-Install workflow

on:
  push:
    branches:
      - master
      - DIGIT-2.9LTS
  workflow_dispatch:
    inputs:
      destroyCommand:
        description: 'Type "destroy" to run the terraform_infra_destruction job.'
        required: true
        default: ''  

jobs:
  check-changed-files:
    runs-on: ubuntu-latest
    outputs:
      deploy-as-code-changed: ${{ steps.check_files.outputs.deploy-as-code-changed }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Check for changes in deploy-as-code
      id: check_files
      uses: tj-actions/changed-files@v42
      with:
        files: |
          deploy-as-code/**

  DIGIT-deployment:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: "true"
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION:  ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_REGION:  ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download infra-as-code folder from artifacts
        uses: actions/download-artifact@v4
        with:
          name: infra-as-code-artifact
          path: .

      - name: Download deploy-as-code folder from artifacts
        uses: actions/download-artifact@v4
        with:
          name: deploy-as-code-artifact
          path: .

      - name: Extract infra-as-code folder
        run: tar -xzf infra-as-code.tar.gz

      - name: Extract deploy-as-code folder
        run: tar -xzf deploy-as-code.tar.gz 

      - name: Convert YAML to ENV
        uses: dcarbone/yaml-to-env-action@main
        with:
          yaml-file: infra-as-code/terraform/sample-aws/input.yaml
          debug: true

      # Install required dependencies
      - name: Install dependencies
        run: sudo apt-get install -y jq

      - name: Convert YAML to JSON
        run: |
          cat deploy-as-code/charts/environments/env-secrets.yaml | yq e -o=json - > secrets.json

      - name: Extract flywayPassword
        id: extract
        run: |
          db_password=$(jq -r '.secrets.db.password' secrets.json)
          echo "db_password=$db_password" >> $GITHUB_ENV

      - name: Install AWS IAM Authenticator
        run: |
          curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/aws-iam-authenticator
          chmod +x ./aws-iam-authenticator
          sudo mv ./aws-iam-authenticator /usr/local/bin/aws-iam-authenticator
          aws-iam-authenticator version  

      - name: Generate kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name $CLUSTER_NAME
          cat ~/.kube/config > kubeconfig

      - name: Creating namespace
        run: kubectl create namespace egov
        continue-on-error: true

      - name: Verify kubectl get nodes
        run: |
          kubectl get nodes
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION:  ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_REGION:  ${{ secrets.AWS_REGION }}

      - name: Install sops
        run: |
          sudo apt update
          sudo apt install -y gnupg
          wget https://github.com/mozilla/sops/releases/download/v3.7.1/sops-v3.7.1.linux
          chmod +x sops-v3.7.1.linux
          sudo mv sops-v3.7.1.linux /usr/local/bin/sops

      - name: Install Helmfile
        run: |
          HELMFILE_VERSION="v0.140.0"
          curl -L "https://github.com/roboll/helmfile/releases/download/${HELMFILE_VERSION}/helmfile_linux_amd64" -o helmfile
          chmod +x helmfile
          sudo mv helmfile /usr/local/bin/helmfile
          helm plugin install https://github.com/databus23/helm-diff
          helmfile --version

      - name: digit deployment
        run: helmfile -f digit-helmfile.yaml apply --include-needs=true
        working-directory: deploy-as-code 

      - name: Displaying the Loadbalancer ID
        run: |
          LB_ID=$(kubectl get svc ingress-nginx-controller -n backbone -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          echo "LoadBalancer ID: $LB_ID"
          echo "Thank you for installing DIGIT! 🙏 Your installation is complete and ready to roll! 🚀"
          echo "Please map the LoadBalancer ID ($LB_ID) with the domain provided in input.yaml to access the DIGIT UI"
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION:  ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_REGION:  ${{ secrets.AWS_REGION }}
