# Common Labels
labels:
  app: "uba-ui"
  group: "egov"

namespace: egov    

# Ingress Configs
ingress:
  enabled: true
  context: "uba-ui"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "ttpldevops/uba-frontend"
  tag: main
replicas: "1"
httpPort: 80
healthChecks:
  enabled: false
  livenessProbePath: "/uba-ui/"
  readinessProbePath: "/uba-ui/"

extraVolumes: |
  - name: uba-ui
    configMap:
      name: uba-ui

extraVolumeMounts: |
  - mountPath: /usr/share/nginx/html
    name: uba-ui
